<?php
    $this->headLink()->appendStylesheet('/css/jobs.css');
?>
<h1><?php echo $this->escapeHtml($this->category->getName()); ?></h1>
<table class="jobs">
    <tbody>
        <?php foreach($this->jobs as $job): ?>
        <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
            <td class="location"><?php echo $this->escapeHtml($job->getLocation()); ?></td>
            <td class="position">
                <a href="<?php echo $this->url('job', array('action'=>'get', 'id'=>$job->getIdJob()));?>">
                    <?php echo $this->escapeHtml($job->getPosition()); ?>
                </a>
            </td>
            <td class="company">
                <?php echo $this->escapeHtml($job->getCompany()); ?>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
